### ISSUE TITLE
关于字体反爬题目1的提问

### ISSUE THREAD

**Issue by Ccj0203** [TurboWay/glidedsky#2]
https://github.com/TurboWay/glidedsky/blob/4a39e12beb335100349c29851c569a1d18a79377/crawler-font-puzzle-1.py#L33
大佬！能不能请问一下字体反爬题目1第33行这个path是怎么来的，我看到后面的代码中直接批注的是“打开本地的tff文件”，为啥是本地的呢？以及这个path是怎么找到的呢？

**Comment by TurboWay** [comment]
字体文件需要下载到本地，自定义的path，用完即删除。我刚刚改成直接使用临时文件了。
